### ISSUE TITLE
jinja2 can't use django-bootstrap3

### ISSUE THREAD

**Issue by pyth0nboy** [zostera/django-bootstrap3#129]
jinja2 can't use django-bootstrap3

Encountered unknown tag 'load'.

**Comment by potpath** [comment]
This can be done using https://github.com/niwinz/django-jinja.
In my case, I want to use `bootstrap_form` template tag in Jinja2.

* In `settings.py`, add the following `TEMPLATES`
```Python
{
    "BACKEND": "django_jinja.backend.Jinja2",
    "OPTIONS": {
        "globals": {
            "bootstrap_form": "bootstrap3.templatetags.bootstrap3.bootstrap_form",
        },
    },
}
```
* In Jinja2 template, use it as global function, like following
```Django
{{ bootstrap_form(form)|safe }}
```
The `safe` filter is mandatory because `Django 1.8` set `'autoescape': True` by default.

**Comment by rocktavious** [comment]
This works when your using django-jinja.  But Django has its own template engine for jinja2 now, and this does not work with that.  I had to do something like this to get it to work with that template engine
* In `settings.py`
```
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'myapp.jinja2.environment'
        }
    },
```
* in `myapp.jinja2.py`
```
from bootstrap3.forms import render_form, render_formset
from jinja2 import Environment


def environment(**options):
    env = Environment(**options)
    env.globals.update({
        'bootstrap_form': render_form,
        'bootstrap_formset': render_formset,
    })
    return env
```
